amcl:
  ros__parameters:
    use_sim_time: false
    robot_model_type: differential

controller_server:
  ros__parameters:
    controller_frequency: 20.0
    minimum_velocity_threshold: 0.6  # As per your requirement

planner_server:
  ros__parameters:
    expected_planner_frequency: 1.0

bt_navigator:
  ros__parameters:
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
